// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneAdvisor.Data;

namespace OneAdvisor.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200203184342_indexUpdate")]
    partial class indexUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("idn_RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("idn_UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("idn_UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("idn_UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("idn_UserToken");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternateIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaidenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MarriageDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MarritalStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("MarritalStatusId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("clt_Client");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContactTypeId");

                    b.ToTable("clt_Contact");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.ClientTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clt_ClientType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27bb22b3-4c3d-41a3-48bf-690a98f8f780"),
                            Code = "individual",
                            DisplayOrder = 1,
                            Name = "Individual"
                        },
                        new
                        {
                            Id = new Guid("295565bf-7485-85f1-6c98-947ab0b7770c"),
                            Code = "company",
                            DisplayOrder = 2,
                            Name = "Company"
                        },
                        new
                        {
                            Id = new Guid("55f6c0ef-ae2c-faac-adff-ea3bd269043f"),
                            Code = "trust",
                            DisplayOrder = 3,
                            Name = "Trust"
                        },
                        new
                        {
                            Id = new Guid("bc0b4043-25cc-dbb6-cfd5-981557a10ca1"),
                            Code = "unknown",
                            DisplayOrder = 4,
                            Name = "Unknown Entity"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.ContactTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clt_ContactType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6349e22-3e27-404a-8584-58e420510834"),
                            Name = "Cellphone Number"
                        },
                        new
                        {
                            Id = new Guid("b3c261d0-4e1d-4dd8-b944-6d6afd1795e0"),
                            Name = "Email Address"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.MarritalStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clt_MarritalStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77fa3769-7775-4cdd-b5d4-8b526b2d894c"),
                            Name = "Single"
                        },
                        new
                        {
                            Id = new Guid("5f7a5d69-845c-4f8d-b108-7c70084f3f6a"),
                            Name = "Married COP"
                        },
                        new
                        {
                            Id = new Guid("b31331ec-73cb-4985-aa93-e60e04a48095"),
                            Name = "Married ANC"
                        },
                        new
                        {
                            Id = new Guid("b16cbd3b-cf50-4a74-8f38-a8ca6b1cb83f"),
                            Name = "Married ANC (with Accrual)"
                        },
                        new
                        {
                            Id = new Guid("e4f03497-5dbf-4bd0-bc14-660a3969f011"),
                            Name = "Widowed"
                        },
                        new
                        {
                            Id = new Guid("91ebd765-bd8b-4908-94dc-00f09fe37ca7"),
                            Name = "Divorced"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PolicyProductTypeId");

                    b.ToTable("clt_PolicyProduct");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTypeId");

                    b.ToTable("clt_PolicyProductType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95b24f26-5d16-0289-ea4d-754603c3e950"),
                            Code = "med_medical_aid",
                            Name = "Medical Aid",
                            PolicyTypeId = new Guid("023107f5-97a6-456d-9182-7bbda72ca82a")
                        },
                        new
                        {
                            Id = new Guid("f6db6be4-2672-7063-6920-ae95a0130b73"),
                            Code = "med_gap_cover",
                            Name = "Gap Cover",
                            PolicyTypeId = new Guid("023107f5-97a6-456d-9182-7bbda72ca82a")
                        },
                        new
                        {
                            Id = new Guid("0269860e-a5ab-7912-e65a-539c124d5593"),
                            Code = "med_add_medical_savings",
                            Name = "Extra Medical Savings",
                            PolicyTypeId = new Guid("023107f5-97a6-456d-9182-7bbda72ca82a")
                        },
                        new
                        {
                            Id = new Guid("178c71d8-f378-fc92-6347-149108b4f24f"),
                            Code = "life_life_insurance",
                            Name = "Life Insurance",
                            PolicyTypeId = new Guid("f3d877b4-1800-4711-8cc9-35169f8bd60b")
                        },
                        new
                        {
                            Id = new Guid("0c55f316-f446-a8f8-488c-ac1eb587a9c9"),
                            Code = "inv_unit_trust",
                            Name = "Unit Trust",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("3b7ccd1e-44b5-d81e-b6b4-18c56c1c077f"),
                            Code = "inv_endowment",
                            Name = "Endowment",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("62007d95-7d61-4182-b998-9ffb4c5fda0b"),
                            Code = "inv_tax_free",
                            Name = "Tax Free Savings",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("4df79496-16cd-9375-eb86-3cbcd8eb47fc"),
                            Code = "inv_preservation_pension",
                            Name = "Preservation Pension",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("5541cf6c-50ef-5fcd-f584-6673a125c817"),
                            Code = "inv_preservation_provident",
                            Name = "Preservation Provident",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("273e862c-abd5-ac36-3bb7-31ea2e18cb9d"),
                            Code = "inv_retirement_annuity",
                            Name = "Retirement Annuity",
                            PolicyTypeId = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9")
                        },
                        new
                        {
                            Id = new Guid("062d7233-f743-9e5a-8c07-d5580bfa11a4"),
                            Code = "short_personal_lines",
                            Name = "Personal Lines",
                            PolicyTypeId = new Guid("a90a5869-4da5-4cce-8973-9a8194c2bdcb")
                        },
                        new
                        {
                            Id = new Guid("67c1d0a3-b5b4-3c23-4256-4e79266f5378"),
                            Code = "short_commercial_lines",
                            Name = "Commercial Lines",
                            PolicyTypeId = new Guid("a90a5869-4da5-4cce-8973-9a8194c2bdcb")
                        },
                        new
                        {
                            Id = new Guid("da086441-91a9-6e5e-5ad6-3167b2076329"),
                            Code = "rewards_rewards_program",
                            Name = "Rewards Program",
                            PolicyTypeId = new Guid("3d991459-2043-46b9-9357-5446a993b81d")
                        },
                        new
                        {
                            Id = new Guid("a202bce5-8e20-a795-1a38-c93b0cfd41ac"),
                            Code = "group_scheme_pension",
                            Name = "Pension Fund",
                            PolicyTypeId = new Guid("8fe8751f-c4f0-01c5-26bd-a92f918651d2")
                        },
                        new
                        {
                            Id = new Guid("988d7de4-1760-f6e8-b9c2-c68e4d95e7e2"),
                            Code = "group_scheme_provident",
                            Name = "Provident Fund",
                            PolicyTypeId = new Guid("8fe8751f-c4f0-01c5-26bd-a92f918651d2")
                        },
                        new
                        {
                            Id = new Guid("bdb36139-07a5-13aa-7431-128329c3bb28"),
                            Code = "group_scheme_risk",
                            Name = "Group Risk",
                            PolicyTypeId = new Guid("8fe8751f-c4f0-01c5-26bd-a92f918651d2")
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.PolicyTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("clt_PolicyType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a98bb718-4acb-4fad-afe9-5fbba00203b9"),
                            Code = "investment",
                            DisplayOrder = 1,
                            Name = "Investment"
                        },
                        new
                        {
                            Id = new Guid("f3d877b4-1800-4711-8cc9-35169f8bd60b"),
                            Code = "life_insurance",
                            DisplayOrder = 2,
                            Name = "Life Insurance"
                        },
                        new
                        {
                            Id = new Guid("a90a5869-4da5-4cce-8973-9a8194c2bdcb"),
                            Code = "short_term",
                            DisplayOrder = 3,
                            Name = "Short Term Insurance"
                        },
                        new
                        {
                            Id = new Guid("023107f5-97a6-456d-9182-7bbda72ca82a"),
                            Code = "medical_cover",
                            DisplayOrder = 4,
                            Name = "Medical Cover"
                        },
                        new
                        {
                            Id = new Guid("3d991459-2043-46b9-9357-5446a993b81d"),
                            Code = "rewards",
                            DisplayOrder = 5,
                            Name = "Rewards Program"
                        },
                        new
                        {
                            Id = new Guid("8fe8751f-c4f0-01c5-26bd-a92f918651d2"),
                            Code = "group_scheme",
                            DisplayOrder = 6,
                            Name = "Group scheme"
                        },
                        new
                        {
                            Id = new Guid("c498f023-a7c9-f6c3-e021-c265972a209c"),
                            Code = "unknown",
                            DisplayOrder = 7,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.PolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PolicyProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Premium")
                        .HasColumnType("Money");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PolicyProductId");

                    b.HasIndex("PolicyProductTypeId");

                    b.HasIndex("PolicyTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("clt_Policy");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionAllocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromClientId");

                    b.HasIndex("ToClientId");

                    b.ToTable("com_CommissionAllocation");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionAllocationPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommissionAllocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommissionAllocationId");

                    b.HasIndex("PolicyId");

                    b.ToTable("com_CommissionAllocationPolicy");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountIncludingVAT")
                        .HasColumnType("Money");

                    b.Property<Guid>("CommissionStatementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommissionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SplitGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VAT")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.HasIndex("CommissionStatementId");

                    b.HasIndex("CommissionTypeId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId", "CommissionStatementId", "CommissionTypeId", "PolicyId")
                        .HasName("INDEX_Commission_UserId_CommissionStatementId");

                    b.ToTable("com_Commission");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionErrorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommissionStatementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommissionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CommissionStatementId");

                    b.HasIndex("PolicyId");

                    b.ToTable("com_CommissionError");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionSplitRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Split")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("com_CommissionSplitRule");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionSplitRulePolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommissionSplitRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommissionSplitRuleId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("com_CommissionSplitRulePolicy");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionStatementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountIncludingVAT")
                        .HasColumnType("Money");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateYear")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<decimal>("VAT")
                        .HasColumnType("Money");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("com_CommissionStatement");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionStatementTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("com_CommissionStatementTemplate");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.Lookup.CommissionEarningsTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("com_CommissionEarningsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b42edc0-fac6-e946-c779-9d90a805c294"),
                            DisplayOrder = 0,
                            Name = "Monthly Annuity"
                        },
                        new
                        {
                            Id = new Guid("e8799015-6f4a-5d45-5be9-0fcd516e0951"),
                            DisplayOrder = 1,
                            Name = "Annual Annuity"
                        },
                        new
                        {
                            Id = new Guid("e7f98561-f018-3edd-2118-e3646c89e2a2"),
                            DisplayOrder = 2,
                            Name = "Life 1st Years"
                        },
                        new
                        {
                            Id = new Guid("9f8fc29d-0f1c-b952-d446-79cc3ed967d7"),
                            DisplayOrder = 3,
                            Name = "Once Off Commissions"
                        },
                        new
                        {
                            Id = new Guid("27ec936b-5db7-64b8-1a1b-5edb3b56a20d"),
                            DisplayOrder = 4,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.Lookup.CommissionTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CommissionEarningsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CommissionEarningsTypeId");

                    b.HasIndex("PolicyTypeId");

                    b.ToTable("com_CommissionType");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.ApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dir_Application");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "Directory"
                        },
                        new
                        {
                            Id = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Client"
                        },
                        new
                        {
                            Id = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Commission"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("dir_AuditLog");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.BranchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("dir_Branch");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.ChangeLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dir_ChangeLog");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.Lookup.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommissionPolicyNumberPrefixes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dir_Company");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.Lookup.UserTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dir_UserType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70a67bcf-f8d3-8fe7-9c3e-b4b8b9bf9cc8"),
                            DisplayOrder = 1,
                            Name = "Broker"
                        },
                        new
                        {
                            Id = new Guid("442f9050-bde4-9aa6-75f5-a9a7e5f84a5c"),
                            DisplayOrder = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d3155541-8b53-64d7-343e-57d6e5c959db"),
                            DisplayOrder = 3,
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.Lookup.VATRateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dir_VATRate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("327abe6a-c200-2e53-ba63-e665174438b9"),
                            EndDate = new DateTime(2018, 3, 31, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            Rate = 14m
                        },
                        new
                        {
                            Id = new Guid("490e393a-71bb-b54c-99cf-87ca4e8a88dc"),
                            Rate = 15m,
                            StartDate = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.OrganisationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("'{ }'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("VATRegistered")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("VATRegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dir_Organisation");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("idn_Role");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.RoleToUseCaseEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(32);

                    b.Property<string>("UseCaseId")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("RoleId", "UseCaseId");

                    b.HasIndex("UseCaseId");

                    b.ToTable("dir_RoleToUseCase");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.UseCaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("dir_UseCase");

                    b.HasData(
                        new
                        {
                            Id = "dir_view_users",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "View Users"
                        },
                        new
                        {
                            Id = "dir_edit_users",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "Edit Users"
                        },
                        new
                        {
                            Id = "dir_view_organisations",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "View Organisations"
                        },
                        new
                        {
                            Id = "dir_edit_organisations",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "Edit Organisations"
                        },
                        new
                        {
                            Id = "dir_view_branches",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "View Branches"
                        },
                        new
                        {
                            Id = "dir_edit_branches",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "Edit Branches"
                        },
                        new
                        {
                            Id = "dir_view_roles",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = "dir_edit_roles",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "Edit Roles"
                        },
                        new
                        {
                            Id = "dir_view_audit_logs",
                            ApplicationId = new Guid("66c3b4e8-8a30-4a4b-be4d-3928d12fefe9"),
                            Name = "View Audit Logs"
                        },
                        new
                        {
                            Id = "clt_view_clients",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "View Clients"
                        },
                        new
                        {
                            Id = "clt_edit_clients",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Edit Clients"
                        },
                        new
                        {
                            Id = "clt_view_policies",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "View Policies"
                        },
                        new
                        {
                            Id = "clt_edit_policies",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Edit Policies"
                        },
                        new
                        {
                            Id = "clt_view_contacts",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "View Contacts"
                        },
                        new
                        {
                            Id = "clt_edit_contacts",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Edit Contacts"
                        },
                        new
                        {
                            Id = "clt_import_clients",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Import Clients"
                        },
                        new
                        {
                            Id = "clt_export_clients",
                            ApplicationId = new Guid("605ea52c-3627-48e2-8f7c-4819c5ea555b"),
                            Name = "Export Clients"
                        },
                        new
                        {
                            Id = "com_import_commissions",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Import Commissions"
                        },
                        new
                        {
                            Id = "com_view_commissions",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commissions"
                        },
                        new
                        {
                            Id = "com_edit_commissions",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Edit Commissions"
                        },
                        new
                        {
                            Id = "com_view_commission_statements",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Statements"
                        },
                        new
                        {
                            Id = "com_edit_commission_statements",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Edit Commission Statements"
                        },
                        new
                        {
                            Id = "com_view_report_client_revenue",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Client Revenue Report"
                        },
                        new
                        {
                            Id = "com_view_commission_allocations",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Allocations"
                        },
                        new
                        {
                            Id = "com_edit_commission_allocations",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Edit Commission Allocations"
                        },
                        new
                        {
                            Id = "com_view_report_user_monthly_commission",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission User Monthly Commission Report"
                        },
                        new
                        {
                            Id = "com_edit_commission_split_rules",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "Edit Commission Split Rules"
                        },
                        new
                        {
                            Id = "com_view_commission_split_rules",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Split Rules"
                        },
                        new
                        {
                            Id = "com_view_report_past_revenue_commission",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Projections Report"
                        },
                        new
                        {
                            Id = "com_view_report_commission_lapse",
                            ApplicationId = new Guid("2fca4500-9142-4940-aaf4-b18925c96d66"),
                            Name = "View Commission Lapse Report"
                        });
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("'70a67bcf-f8d3-8fe7-9c3e-b4b8b9bf9cc8'");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserTypeId");

                    b.ToTable("idn_User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.ClientEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.ClientTypeEntity", "ClientType")
                        .WithMany()
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.MarritalStatusEntity", "MarritalStatus")
                        .WithMany()
                        .HasForeignKey("MarritalStatusId");

                    b.HasOne("OneAdvisor.Data.Entities.Directory.OrganisationEntity", "Organisation")
                        .WithMany("Clients")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.ContactEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.ClientEntity", "Client")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.ContactTypeEntity", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.Lookup.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductTypeEntity", "PolicyProductType")
                        .WithMany()
                        .HasForeignKey("PolicyProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductTypeEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyTypeEntity", "PolicyType")
                        .WithMany("PolicyProductTypes")
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Client.PolicyEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.ClientEntity", "Client")
                        .WithMany("ClientPolicies")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.Lookup.CompanyEntity", "Company")
                        .WithMany("ClientPolicies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductEntity", "PolicyProduct")
                        .WithMany("Policies")
                        .HasForeignKey("PolicyProductId");

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyProductTypeEntity", "PolicyProductType")
                        .WithMany("Policies")
                        .HasForeignKey("PolicyProductTypeId");

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyTypeEntity", "PolicyType")
                        .WithMany("Policies")
                        .HasForeignKey("PolicyTypeId");

                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionAllocationEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.ClientEntity", "FromClient")
                        .WithMany("FromCommissionAllocations")
                        .HasForeignKey("FromClientId")
                        .HasConstraintName("ForeignKey_FromClient_FromCommissionAllocations")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.ClientEntity", "ToClient")
                        .WithMany("ToCommissionAllocations")
                        .HasForeignKey("ToClientId")
                        .HasConstraintName("ForeignKey_ToClient_ToCommissionAllocations")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionAllocationPolicyEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Commission.CommissionAllocationEntity", "CommissionAllocation")
                        .WithMany("CommissionAllocationPolicies")
                        .HasForeignKey("CommissionAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.PolicyEntity", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Commission.CommissionStatementEntity", "CommissionStatement")
                        .WithMany("Commissions")
                        .HasForeignKey("CommissionStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Commission.Lookup.CommissionTypeEntity", "CommissionType")
                        .WithMany()
                        .HasForeignKey("CommissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.PolicyEntity", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", "User")
                        .WithMany("Commissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionErrorEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Client.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("OneAdvisor.Data.Entities.Commission.CommissionStatementEntity", "CommissionStatement")
                        .WithMany("CommissionErrors")
                        .HasForeignKey("CommissionStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.PolicyEntity", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionSplitRuleEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", "User")
                        .WithMany("CommissionSplitRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionSplitRulePolicyEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Commission.CommissionSplitRuleEntity", "CommissionSplitRule")
                        .WithMany("CommissionSplitRulePolicy")
                        .HasForeignKey("CommissionSplitRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.PolicyEntity", "Policy")
                        .WithMany("CommissionSplitRulePolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.CommissionStatementEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.Lookup.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.OrganisationEntity", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Commission.Lookup.CommissionTypeEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Commission.Lookup.CommissionEarningsTypeEntity", "CommissionEarningsType")
                        .WithMany()
                        .HasForeignKey("CommissionEarningsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Client.Lookup.PolicyTypeEntity", "PolicyType")
                        .WithMany("CommissionTypes")
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.AuditLogEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.UserEntity", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.BranchEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.OrganisationEntity", "Organisation")
                        .WithMany("Branches")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.RoleEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.RoleToUseCaseEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.RoleEntity", "Role")
                        .WithMany("RoleToUseCases")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.UseCaseEntity", "UseCase")
                        .WithMany("RoleToUseCases")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.UseCaseEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.ApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneAdvisor.Data.Entities.Directory.UserEntity", b =>
                {
                    b.HasOne("OneAdvisor.Data.Entities.Directory.BranchEntity", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneAdvisor.Data.Entities.Directory.Lookup.UserTypeEntity", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
