# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core





jobs:
- job: Api Build
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
- job: Web Build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      cd web
      npm install
      npm run flow
      npm test
      npm run build
