# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
  - job: api_build
    pool:
      vmImage: "Ubuntu 16.04"
    variables:
      buildConfiguration: "Release"
    steps:
      - script: |
          dotnet restore
        displayName: "dotnet restore"
      - script: |
          dotnet test
        displayName: "dotnet test"
      - script: |
          dotnet publish --configuration $(buildConfiguration)
        displayName: "dotnet publish $(buildConfiguration)"
      - task: CopyFiles@2
        inputs:
          artifactName: "api"
          sourceFolder: "api/bin/Release/netcoreapp2.1/publish"
          targetFolder: "$(Build.ArtifactStagingDirectory)/api"
  - job: web_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - script: |
          npm install
        displayName: "npm install"
        workingDirectory: "web"
      - script: |
          npm run check-types
          npm run test
        displayName: "npm test"
        workingDirectory: "web"
      - script: |
          npm run build
        displayName: "npm build"
        workingDirectory: "web"
      - script: |
          npm install
        displayName: "npm install (server)"
        workingDirectory: "web/server"
      - task: CopyFiles@2
        inputs:
          artifactName: "web"
          sourceFolder: "web/server"
          targetFolder: "$(Build.ArtifactStagingDirectory)/web"
