# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
    - job: landing_build
      pool:
          vmImage: "Ubuntu 16.04"
      steps:
          - script: |
                npm install
            displayName: "install client packages"
            workingDirectory: "oneadvisor/landing"
          - script: |
                npm run check-types
            displayName: "check types"
            workingDirectory: "oneadvisor/landing"
          - script: |
                npm install
            displayName: "install server packages"
            workingDirectory: "oneadvisor/landing/server"
          - script: |
                npm run build:production
            displayName: "build: production"
            workingDirectory: "oneadvisor/landing"
          - task: CopyFiles@2
            inputs:
                sourceFolder: "oneadvisor/landing/server"
                targetFolder: $(Build.ArtifactStagingDirectory)
                cleanTargetFolder: true
          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: $(Build.ArtifactStagingDirectory)
                artifactName: landing.production
