# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
    - job: api_build
      pool:
          vmImage: "Ubuntu 16.04"
      variables:
          buildConfiguration: "Release"
      steps:
          - task: DotNetCoreInstaller@0
            displayName: "Use .NET Core SDK Tool Installer"
            inputs:
                version: 2.2.100
          - script: |
                dotnet restore
            displayName: "restore packages"
          - script: |
                dotnet test
            displayName: "run tests"
          - script: |
                dotnet publish --configuration $(buildConfiguration) /p:Version=0.6.0
            displayName: "publish for $(buildConfiguration)"
          - task: CopyFiles@2
            inputs:
                sourceFolder: "oneadvisor/api/bin/$(buildConfiguration)/netcoreapp2.2/publish"
                targetFolder: $(Build.ArtifactStagingDirectory)
                cleanTargetFolder: true
          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: $(Build.ArtifactStagingDirectory)
                artifactName: api
    - job: web_build
      pool:
          vmImage: "Ubuntu 16.04"
      steps:
          - script: |
                npm install
            displayName: "install client packages"
            workingDirectory: "oneadvisor/web"
          - script: |
                npm run check-types
            displayName: "check types"
            workingDirectory: "oneadvisor/web"
          - script: |
                npm run test
            displayName: "run tests"
            workingDirectory: "oneadvisor/web"
          - script: |
                npm install
            displayName: "install server packages"
            workingDirectory: "oneadvisor/web/server"
          - script: |
                npm run build:staging
            displayName: "build: staging"
            workingDirectory: "oneadvisor/web"
          - task: CopyFiles@2
            inputs:
                sourceFolder: "oneadvisor/web/server"
                targetFolder: $(Build.ArtifactStagingDirectory)
                cleanTargetFolder: true
          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: $(Build.ArtifactStagingDirectory)
                artifactName: web.staging
          - script: |
                npm run build:production
            displayName: "build: production"
            workingDirectory: "oneadvisor/web"
          - task: CopyFiles@2
            inputs:
                sourceFolder: "oneadvisor/web/server"
                targetFolder: $(Build.ArtifactStagingDirectory)
                cleanTargetFolder: true
          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: $(Build.ArtifactStagingDirectory)
                artifactName: web.production
