jobs:
  - job: api_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - displayName: "dotnet restore"
        script: "dotnet restore"
      - displayName: "dotnet test"
        script: "dotnet test"
      - displayName: "dotnet build $(buildConfiguration)"
        script: "dotnet build --configuration $(buildConfiguration)"
    variables:
      buildConfiguration: Release
  - job: web_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - displayName: "npm install"
        script: "npm install"
        workingDirectory: web
      - displayName: "npm test"
        script: |
          npm run check-types
          npm run test
        workingDirectory: web
      - displayName: "npm build"
        script: "npm run build"
        workingDirectory: web
  - job: web_server_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - displayName: "npm install"
        script: "npm install"
        workingDirectory: web/server
