--TO RUN: Shift + Cmd + E

--SELECT name FROM master.sys.databases

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='OneAdvisor'
Order by TABLE_NAME
